### ISSUE TITLE
Extending the project schema

### ISSUE THREAD

**Issue by simenandre** [bjerkio/studio#8]
We should be able to insert both titles and project names. The reasoning behind this is that we probably want a _title_, meaning something that tells a story in combination with a project name. An example would be:

Name: Membership System
Project Title: Digitalizalized membership readily available for volunteers, members and staff.

We probably also want to add some technical fields as well, such as defining a slug and social media metadata. I even suggest adding https://www.sanity.io/plugins/seo-pane

**Comment by HanBrustad** [comment]
Would "project description" suit more, rather than "project title"? 
Name and Title have similar meaning in this, in my opinion.

**Comment by simenandre** [comment]
We do have a field for project description already.

I think we should rename the _mission statement_ and replace it with preamble.

![Skjermbilde 2023-06-12 kl  12 17 18](https://github.com/bjerkio/studio/assets/3726815/25d9aa57-fcdc-41ab-87f8-f27c5cb59387)

So, that means «Norges største [..] takster» would be _project title_, the next text would be the preamble.

In our current project list, we use the project name and short description, as such:

![Skjermbilde 2023-06-12 kl  12 18 08](https://github.com/bjerkio/studio/assets/3726815/014c278e-3a1b-47ae-aec2-e7628cd9a411)
